database:
  url: mongodb+srv://neighborlysocialapp:cluster01@cluster0.cncxy2q.mongodb.net/
  name: Neighborly-production
  collection: users
  pgHost: 34.207.25.173
  pgUser: postgres
  pgPassword: N3ighborly
  pgDB: postgres
  pgPort: 5432
  contents: content
  contentVotes: content_votes
  comments: comments
  commentVotes: comment_votes
